# Generated by Django 6.0.7 on 2026-07-22 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        ('Recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='Recommender.project'),
        ),
    ]
